import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/providers/providers";
import Header from "@/components/common/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Olle Burlin Starter",
  description: "Generated by create next app with my modifications",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div id="wrapper" className="flex flex-col min-h-screen">
            <Header />
            <div className="flex-1 bg-gray-100">{children}</div>
            <footer className="p-4 text-center">&copy; Olle Burlin</footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}

// function Icons() {
//   return (
//     <>
//       <link
//         rel="apple-touch-icon"
//         sizes="57x57"
//         href="/icons/apple-icon-57x57.png"
//       />
//       <link
//         rel="apple-touch-icon"
//         sizes="60x60"
//         href="/icons/apple-icon-60x60.png"
//       />
//       <link
//         rel="apple-touch-icon"
//         sizes="72x72"
//         href="/icons/apple-icon-72x72.png"
//       />
//       <link
//         rel="apple-touch-icon"
//         sizes="76x76"
//         href="/icons/apple-icon-76x76.png"
//       />
//       <link
//         rel="apple-touch-icon"
//         sizes="114x114"
//         href="/icons/apple-icon-114x114.png"
//       />
//       <link
//         rel="apple-touch-icon"
//         sizes="120x120"
//         href="/icons/apple-icon-120x120.png"
//       />
//       <link
//         rel="apple-touch-icon"
//         sizes="144x144"
//         href="/icons/apple-icon-144x144.png"
//       />
//       <link
//         rel="apple-touch-icon"
//         sizes="152x152"
//         href="/icons/apple-icon-152x152.png"
//       />
//       <link
//         rel="apple-touch-icon"
//         sizes="180x180"
//         href="/icons/apple-icon-180x180.png"
//       />
//       <link
//         rel="icon"
//         type="image/png"
//         sizes="192x192"
//         href="/icons/android-icon-192x192.png"
//       />
//       <link
//         rel="icon"
//         type="image/png"
//         sizes="32x32"
//         href="/icons/favicon-32x32.png"
//       />
//       <link
//         rel="icon"
//         type="image/png"
//         sizes="96x96"
//         href="/icons/favicon-96x96.png"
//       />
//       <link
//         rel="icon"
//         type="image/png"
//         sizes="16x16"
//         href="/icons/favicon-16x16.png"
//       />

//       <meta name="msapplication-TileColor" content="#ECF8F5" />
//       <meta
//         name="msapplication-TileImage"
//         content="/icons/ms-icon-144x144.png"
//       />
//       <meta name="theme-color" content="#ECF8F5" />
//     </>
//   );
// }
