import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Olle Burlin Starter",
  description: "Generated by create next app with my modifications",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
